# Generated by Django 4.2.2 on 2023-07-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=1000)),
                ('Status', models.CharField(max_length=60)),
                ('Date', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousComplaintUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(default='', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=200)),
                ('Type_of_complaint', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=1000)),
                ('Status', models.CharField(choices=[('pending', 'pending'), ('process', 'process'), ('solved', 'solved')], max_length=60)),
                ('Date', models.CharField(max_length=20, null=True)),
                ('Email', models.EmailField(default='', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=200)),
                ('Type_of_complaint', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=1000)),
                ('Status', models.CharField(choices=[('pending', 'pending'), ('process', 'process'), ('solved', 'solved')], max_length=60)),
                ('Date', models.CharField(max_length=20, null=True)),
                ('Email', models.EmailField(default='', max_length=254, null=True)),
            ],
        ),
    ]
