# Generated by Django 4.1.3 on 2023-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Contactno', models.IntegerField()),
                ('Course', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=300)),
            ],
        ),
    ]
