# Generated by Django 4.1.3 on 2023-05-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_profile_contactno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='Gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
