# Generated by Django 4.2.2 on 2023-07-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_alter_profile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
