# Generated by Django 4.1.3 on 2023-04-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.CharField(max_length=3000),
        ),
    ]
