# Generated by Django 4.1.3 on 2023-04-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_alter_systemuser_email_alter_systemuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='First_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='Last_name',
            field=models.CharField(max_length=100),
        ),
    ]
