# Generated by Django 4.1.3 on 2023-04-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
