# Generated by Django 4.1.3 on 2023-04-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaper', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='Time',
            field=models.CharField(max_length=100),
        ),
    ]
