# Generated by Django 4.1.3 on 2023-04-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaper', '0005_cppquestions_cquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Sub',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
